name: 'GitHub Action submodule update'
description: 'When branch is pushed to update submodule, create PR in base/parent'
author: 'Marissa Ovenshire'

inputs:
  github_token:
    description: 'Github Token'
    required: true
  checkout_branch:
    description: 'Branch to checkout'
    required: false
    default: 'main'
  pr_against_branch:
    description: 'Parent branch'
    required: true
  parent_repository:
    description: 'Parent Repository'
    required: true
  owner:
    description: 'Owner'
    required: true
  label:
    description: 'submodule update'
    required: false
    default: 'Autogen submodule update'


runs:
  using: 'composite'
  steps:
    - name: Checkout base repo and branch
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ inputs.parent_repository }}
        ref: ${{ inputs.checkout_branch }}
        submodules: true
        fetch-depth: 0 ## hopefully if stuff is squashed, we can change to 2 

    - name: co -b new branch in base and push changes
      shell: bash
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git submodule update --remote

        BRANCH_NAME=submodule-update-${GITHUB_RUN_ID}-tmp
        git checkout -b "$BRANCH_NAME"

        if ! git diff --quiet; then
          # Get the staged diff so ik what submodule sha is being set 
          SUBMODULE_DIFF="$(git diff --cached)"
          COMMIT_MSG="[AUTOGEN] Submodule updates based on sha ${GITHUB_SHA} \n ${SUBMODULE_UPDATES} \n Diff: ${SUBMODULE_DIFF}"

          git commit -am "$COMMIT_MSG"
          git push --set-upstream origin "$BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV


          ## OPTION 1 commit directly

          # Checkout the target branch
          git checkout ${{ inputs.pr_against_branch }}

          # Merge the changes from the temporary branch
          git merge "$BRANCH_NAME"

          # Push the changes to the target branch
          git push origin ${{ inputs.pr_against_branch }}

          # Delete the temporary branch
          git branch -d "$BRANCH_NAME"
          git push origin --delete "$BRANCH_NAME"

        else
          echo "No submodule changes to commit"
          exit 0
        fi

    # - name: Create pull request against target branch
    #   uses: actions/github-script@v5
    #   with:
    #     github-token: ${{ inputs.github_token }}
    #     script: |
    #       const repo = '${{ inputs.parent_repository }}'.split('/')[1].trim();
    #       const owner = '${{ inputs.owner }}';
    #       const branch = process.env.BRANCH_NAME;
    #       const prTitle = `[Auto-generated] Submodule Updates ${branch}`;

    #       try {
    #         await github.rest.pulls.create({
    #           owner,
    #           repo,
    #           head: branch,
    #           base: '${{ inputs.pr_against_branch }}',
    #           title: prTitle,
    #           body: prTitle,
    #         });
    #       } catch (err) {
    #         core.setFailed(`Failed to create PR: ${err.message}`);
    #       }

    # - name: Add labels to pull request
    #   uses: actions/github-script@v5
    #   with:
    #     github-token: ${{ inputs.github_token }}
    #     script: |
    #       const repo = '${{ inputs.parent_repository }}'.split('/')[1].trim();
    #       const owner = '${{ inputs.owner }}';
    #       const branch = process.env.BRANCH_NAME;
    #       const label = '${{ inputs.label }}';
    #       const { data: pullRequests } = await github.rest.pulls.list({
    #         owner,
    #         repo,
    #         state: 'open'
    #       });
    #       const pr = pullRequests.find(pr => pr.head.ref === branch);
    #       if (!pr) {
    #         core.setFailed(`No open pull request found for branch '${branch}'`);
    #         return;
    #       }
    #       await github.rest.issues.addLabels({
    #         issue_number: pr.number,
    #         owner,
    #         repo,
    #         labels: [label]
    #       });
